name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_DATE: $(date +"%Y-%m-%dT%H:%M:%S")

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag alpine-ghcr-push-test:${{ env.BUILD_DATE }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push GHCR Image
      run: docker push ghcr.io/allanpedaipg/test-ghcr-push:${{ env.BUILD_DATE }}
