name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_DATE: "2023-10-31T135348"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
    - name: Set variables
      shell: bash
      run: |
        echo "BUILD_DATE=$(date +%Y-%m-%dT%H%M%S)" >> $GITHUB_ENV
        GH_REPO=${{ github.repository }}
        echo "GH_REPO=${GH_REPO,,}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  docker build . --file Dockerfile
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push GHCR Image
      run: |
        docker build . --tag ghcr.io/allanpedaipg/${{ env.GH_REPO }}:${{ env.BUILD_DATE }}
        docker push ghcr.io/allanpedaipg/${{ env.GH_REPO }}:${{ env.BUILD_DATE }}
