name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alpine-ghcr-push-test:$(date +%s)
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
#  - name: 'Build and push GHCR Image'
#    run: |
#       docker build . --tag ghcr.io/allanpedaipg/test-ghcr-push:latest
#       docker push ghcr.io/allanpedaipg/test-ghcr-push:latest
